# Generated by Django 3.2.6 on 2023-10-30 21:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(default='white', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GreetingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=256)),
                ('address', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaMenuItem',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('box', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='pizzaria.box')),
                ('toppings', models.ManyToManyField(related_name='_pizzaria_pizzamenuitem_toppings_+', to='pizzaria.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'medium'), ('L', 'Large'), ('xl', 'X-Large')], max_length=32)),
                ('extra_toppings', models.ManyToManyField(related_name='_pizzaria_pizza_extra_toppings_+', to='pizzaria.Topping')),
                ('menu_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pizzaria.pizza')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pizzaria.order')),
                ('remove_toppings', models.ManyToManyField(related_name='_pizzaria_pizza_remove_toppings_+', to='pizzaria.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='GreetingCardInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_message', models.CharField(blank=True, max_length=256, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='pizzaria.greetingcard')),
                ('on_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to='pizzaria.greetingcardinstance')),
            ],
        ),
    ]
